version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      APP_DEBUG: "true"
      APP_ENV: "dev"
      APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: sample_app
      DB_USERNAME: root
      DB_PASSWORD: 'c<y"XDOw'
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sample_app
      MYSQL_USER: root
      MYSQL_PASSWORD: 'c<y"XDOw'
      MYSQL_ROOT_PASSWORD: 'c<y"XDOw'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

